language: php

branches:
  only:
    - master

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.8 WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - WP_CORE_DIR=/tmp/wordpress
  - plugin_slug=$(basename $(pwd))
  - plugin_dir=$WP_CORE_DIR/src/wp-content/plugins/$plugin_slug
  - ls -li
  - mkdir php-codesniffer && curl -L https://github.com/squizlabs/PHP_CodeSniffer/archive/master.tar.gz | tar xz --strip-components=1 -C php-codesniffer
  - mkdir wordpress-coding-standards && curl -L https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/archive/master.tar.gz | tar xz --strip-components=1 -C wordpress-coding-standards
  - cd php-codesniffer
  - scripts/phpcs --config-set installed_paths ../wordpress-coding-standards
  - cd $plugin_dir
  - ls -li
  - phpenv rehash

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - $WP_CORE_DIR/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php
  - phpunit

notifications:
  slack:
    secure: F2MXglycJ4cFMWIuCpv94Ln9R+PRLYVhiKJHhKZjzEC9OajGO8vimN18I0UpuVi+4Fc41PYpVyhDbymFd6Q2s4tjqjRby6t76lIgadgPVj07in8SWV0KA9EDrUqZD3l8JRIC4mwEhYwl5KmPdAUZJMU5KOyx5Z50g16Bg48v/nAd2es6AFDK59DYVjf9geSTvsyj87ccGqEU+4yGmSflyfyQ2YykXSJKwFbZeEeAFmoSwW2PPaHsKRgRDw8sHpsYs7M8yAhGvdkUMuAXh1H335KkXg5boY8+odpv3vUlWMxtyHB1xWA4jCePQgSL7D3WQqqjNbFeKL0+Ns7gz1cLQMa7MyfCGlFwtl2QMCMwRkxwK6QXgqX6fWtZV89FJj9CpEnll35p3Qo/0FP/QWdHVa2rzFIlU3xyq3zg+3tvYM7quRdepIomyvkVDDmuKT+lF7/HBWIkWU3g0Z+oOhWFPX5dLV5qgkMXP3geEl0lrkCxjVxjpwGT107tD7eUU7PlinTtIpARMbFHNWnbGjcstfyrsfJSfL98DHMy3Zz8CvPV0eAraPysBjoHJnXwmx7pThmaKAcPvDlNuRE11ijrSDtO2sVq2ogonro/12HE1hb8wkIjwfSA2LNtSq37Yl8OeNX6UTs8JdhmIjmbA1zUB4p63wMG4T+m9NPBVVh0GO0=

