language: php

sudo: false

# Test main supported versions of PHP and HHVM against latest WP. 5.2 is min supported version.
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0

# Additonal tests against stable PHP (min recommended version is 5.6) and past supported versions of WP.
matrix:
  include:
  - php: 5.6
    env: WP_VERSION=3.8.16 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=3.9.14 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.0.13 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.1.13 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.2.10 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.3.6 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.4.5 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.5.4 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=nightly WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1
  allow_failures:
  - env: WP_VERSION=nightly WP_MULTISITE=0

branches:
  only:
  - master
  - develop

before_script:
  - bash tests/bin/install.sh the_social_links_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - /tmp/wordpress-tests-lib/php-codesniffer/bin/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php
  - phpunit -c phpunit.xml.dist

notifications:
  slack:
    secure: F2MXglycJ4cFMWIuCpv94Ln9R+PRLYVhiKJHhKZjzEC9OajGO8vimN18I0UpuVi+4Fc41PYpVyhDbymFd6Q2s4tjqjRby6t76lIgadgPVj07in8SWV0KA9EDrUqZD3l8JRIC4mwEhYwl5KmPdAUZJMU5KOyx5Z50g16Bg48v/nAd2es6AFDK59DYVjf9geSTvsyj87ccGqEU+4yGmSflyfyQ2YykXSJKwFbZeEeAFmoSwW2PPaHsKRgRDw8sHpsYs7M8yAhGvdkUMuAXh1H335KkXg5boY8+odpv3vUlWMxtyHB1xWA4jCePQgSL7D3WQqqjNbFeKL0+Ns7gz1cLQMa7MyfCGlFwtl2QMCMwRkxwK6QXgqX6fWtZV89FJj9CpEnll35p3Qo/0FP/QWdHVa2rzFIlU3xyq3zg+3tvYM7quRdepIomyvkVDDmuKT+lF7/HBWIkWU3g0Z+oOhWFPX5dLV5qgkMXP3geEl0lrkCxjVxjpwGT107tD7eUU7PlinTtIpARMbFHNWnbGjcstfyrsfJSfL98DHMy3Zz8CvPV0eAraPysBjoHJnXwmx7pThmaKAcPvDlNuRE11ijrSDtO2sVq2ogonro/12HE1hb8wkIjwfSA2LNtSq37Yl8OeNX6UTs8JdhmIjmbA1zUB4p63wMG4T+m9NPBVVh0GO0=
